### ISSUE TITLE
run CIGA algorithm error 

### ISSUE THREAD

**Issue by czstudio** [LFhase/CIGA#3]
when i run `!goodtg --config_path GOOD_configs/GOODCMNIST/color/concept/CIGA.yaml` in colab:

```

2023-05-07` 13:42:38.808831: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-07 13:42:40.848157: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
This logger will substitute general print function

INFO: -----------------------------------
    Task: train
Sun May  7 13:42:43 2023
INFO: Load Dataset GOODCMNIST
Downloading...
From: https://drive.google.com/uc?id=1F2r2kVmA0X07AXyap9Y_rOM6LipDzwhq
To: /content/GOOD/storage/datasets/GOODCMNIST.zip
100%|##########| 719M/719M [00:03<00:00, 225MB/s]
Extracting /content/GOOD/storage/datasets/GOODCMNIST.zip
DEBUG: 05/07/2023 01:43:41 PM : Dataset: {'train': GOODCMNIST(29400), 'id_val': GOODCMNIST(6300), 'id_test': GOODCMNIST(6300), 'val': GOODCMNIST(14000), 'test': GOODCMNIST(14000), 'task': 'Multi-label classification', 'metric': 'Accuracy'}
DEBUG: 05/07/2023 01:43:41 PM :  Data(x=[75, 3], edge_index=[2, 1367], y=[1], pos=[75, 2], color=[1], env_id=[1])
INFO: Loading model...
DEBUG: 05/07/2023 01:43:41 PM : Config model
DEBUG: 05/07/2023 01:43:45 PM : Load training utils
INFO: Epoch 0:
/usr/local/lib/python3.10/dist-packages/torch_geometric/data/in_memory_dataset.py:182: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. The data of the dataset is already cached, so any modifications to `data` will not be reflected when accessing its elements. Clearing the cache now by removing all elements in `dataset._data_list`. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)
/usr/local/lib/python3.10/dist-packages/torch_geometric/data/in_memory_dataset.py:182: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)
  0%|░░░░░░░░░░░░░░░░░░░░| 0/230 [00:01<?, ?it/s]
ERROR: 05/07/2023 01:43:47 PM - utils.py - line 87 : Traceback (most recent call last):
  File "/usr/local/bin/goodtg", line 33, in <module>
    sys.exit(load_entry_point('graph-ood', 'console_scripts', 'goodtg')())
  File "/content/GOOD/GOOD/kernel/main.py", line 69, in goodtg
    main()
  File "/content/GOOD/GOOD/kernel/main.py", line 60, in main
    pipeline.load_task()
  File "/content/GOOD/GOOD/kernel/pipelines/basic_pipeline.py", line 231, in load_task
    self.train()
  File "/content/GOOD/GOOD/kernel/pipelines/basic_pipeline.py", line 113, in train
    train_stat = self.train_batch(data, pbar)
  File "/content/GOOD/GOOD/kernel/pipelines/basic_pipeline.py", line 71, in train_batch
    model_output = self.model(data=data, edge_weight=edge_weight, ood_algorithm=self.ood_algorithm)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GOOD/GOOD/networks/models/CIGAGNN.py", line 73, in forward
    causal_rep = self.get_graph_rep(
  File "/content/GOOD/GOOD/networks/models/CIGAGNN.py", line 108, in get_graph_rep
    return self.feat_encoder(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GOOD/GOOD/networks/models/GINs.py", line 94, in forward
    out_readout = self.encoder(x, edge_index, batch, batch_size, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GOOD/GOOD/networks/models/GINvirtualnode.py", line 118, in forward
    post_conv = self.dropout1(self.relu1(self.batch_norm1(self.conv1(x, edge_index))))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/gin_conv.py", line 80, in forward
    out = self.propagate(edge_index, x=x, size=size)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/message_passing.py", line 476, in propagate
    explain_msg_kwargs = self.inspector.distribute(
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/utils/inspector.py", line 54, in distribute
    for key, param in self.params[func_name].items():
KeyError: 'explain_message'

```

**Comment by LFhase** [comment]
Hi @czstudio can you double check whether the `torch_geometric` version matches that required by GOOD benchmark?

**Comment by LFhase** [comment]
I am closing the issue for now and feel free to re-open it if you have any further questions : )
